### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by MambaDev** [DevWars/devwars-api#28]
Add documentation for each endpoint on each Controller  using the `apidoc` format.

**Comment by VerumEmanio** [comment]
I'm brand new to writing API documentation, and I only know JavaScript, but could I try documenting these endpoints?

**Comment by MambaDev** [comment]
Hi, @VerumEmanio,

This sounds cool if you are interested. DevWars is constantly growing and help is welcome. We are currently in a state which can make it difficult to set up and execute DevWars since it does require some extra parts (which are not used in general use) but is required to start the API. This does not mean you have to start it to be able to contribute. 

The readme/setup is currently being refreshed so there is not a solid setup guide. 

A good place to start would be the `UserProfile.controller.ts`. Since I can easily provide an example response for you (below). You can also look within the `User.controller.ts` file to have a look at ApiDoc examples and what is needed.

```json
{
   "id":1,
   "updatedAt":"1969-12-31T17:00:00.000Z",
   "createdAt":"1969-12-31T17:00:00.000Z",
   "firstName":"asdf",
   "lastName":"asdf",
   "dob":"1998-11-14T00:00:00.000Z",
   "sex":null,
   "about":"abasdf",
   "forHire":true,
   "company":"devwars",
   "websiteUrl":null,
   "addressOne":"776 Bruce Drive",
   "addressTwo":null,
   "city":"East Meadow",
   "state":"New York",
   "zip":"11554",
   "country":"Ecuador",
   "skills":{
      "js":1,
      "css":1,
      "html":1
   }
}
```

Once you have added docs, you can run `npm run serve-docs` and have a look. Any changes would require restarting the docs again to see it the update.

**Comment by VerumEmanio** [comment]
Hi @MambaDev,

Do you have any more sample responses for the remaining endpoints? On that note, would it be easier for me to set up the API and get the responses myself, or for you to send me a list of responses with each endpoint's name?

**Comment by MambaDev** [comment]
Hi @VerumEmanio,

as per my response on the pull request, i'm working on a improved setup guide for the api in which you would be able to setup it. You can currently do that now but you would need a Postgres server, a firebase database. 

Just hold off for a couple of days.

**Comment by VerumEmanio** [comment]
Hi @MambaDev,

Oops, I didn't see that response--sorry about that.

**Comment by MambaDev** [comment]
@VerumEmanio, The README and API implementation is now been reviewed. If you process through the README.md and the CONTRIBUTING.md you should be able to setup the API and have the ability to use it.

**Comment by VerumEmanio** [comment]
Hi @MambaDev,

Per the README instructions to setup the API, I downloaded the latest versions of PostgreSQL and Nodejs. I followed each step exactly. I copied the .env.example file and renamed it with the `.env` file extension, but when I then tried to run `npm run seed`, I got the following message:
```
(node:17428) UnhandledPromiseRejectionWarning: error: password authentication failed for user "MYounge"
    at Connection.parseE (C:\Users\myounge\devwars-api\node_modules\pg\lib\connection.js:604:11)
    at Connection.parseMessage (C:\Users\myounge\devwars-api\node_modules\pg\lib\connection.js:401:19)
    at Socket.<anonymous> (C:\Users\myounge\devwars-api\node_modules\pg\lib\connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
(node:17428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Any idea what's wrong?

**Comment by MambaDev** [comment]
This is stating that the connection for the postgres database is incorrect. Ensure that you have correctly specified the correct postgres database username and password for both test and standard. Ensure that the test and standard databases exist :) 

e.g in postgres `create database devwars; create database devwars_test;`

Hope this helps @VerumEmanio

**Comment by VerumEmanio** [comment]
Hi @MambaDev,

When I open up the SQL Shell and write `create database devwars; create database devwars_test;`, this is what I end up with:
```
Server [localhost]: create database devwars; create database devwars_test;
Database [postgres]:
Port [5432]:
Username [postgres]:
psql: warning: extra command-line argument "create" ignored
psql: warning: extra command-line argument "database" ignored
psql: warning: extra command-line argument "devwars_test;" ignored
psql: warning: extra command-line argument "-U" ignored
psql: warning: extra command-line argument "postgres" ignored
psql: warning: extra command-line argument "-d" ignored
psql: warning: extra command-line argument "postgres" ignored
psql: warning: extra command-line argument "-p" ignored
psql: warning: extra command-line argument "5432" ignored
psql: error: could not connect to server: could not translate host name "create" to address: Unknown host
Press any key to continue . . .
```

In the Environment Variables section of the README when it says 

> Process through the newly created file and make the required changes if needed.

What changes do I need to make to the file with the `.env` extension? Thanks for your help, I've been searching online for answers but haven't found anything I can understand.

**Comment by MambaDev** [comment]
hi @VerumEmanio,

* Just a note, MySQL and Postgres are not the same database, follow this guide on how to setup, connect and use postgres. https://www.guru99.com/postgresql-create-database.html

* If you open the .env you will see it will explain everything you need and what is optional and what is not. e.g 

```bash
# DB_ (Required) - Postgres connection details that are used throughout
# the API to store, read and distribute DevWars information and data.
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=devwars
DB_USER=postgres
DB_PASS=postgres

# FIREBASE_URL (optional) - Use alongside the firebase service account
# json file to connect and communicate with a firebase real-time database.
# This is optional in development but you will be warned each startup 
# about the missing URL.
FIREBASE_URL=
```

Google is your friend when it comes to postgres.

**Comment by VerumEmanio** [comment]
Hi @MambaDev,

Thanks for the guidance. I created the standard and the test devwars databases, and I successfully connected to them as the postgres user via pgAdmin, but when I try to run `npm run seed` from the Node.js command line, I still  get my original error: `(node:17428) UnhandledPromiseRejectionWarning: error: password authentication failed for user "MYounge"`.

Do you know why it's trying to authenticate as the non-existent "MYounge" user instead of the "postgres" user? To solve the issue, I tried setting the postgres user password to `secret` per the .env file. I also tried creating an "MYounge" superuser and setting its password to `secret`. Neither of these options worked. If I try to manually connect via `\c devwars Myounge; `, I type `secret` when prompted for a password but am told that password authentication failed, like this article mentions:
((https://www.postgresql.org/docs/9.1/client-authentication-problems.html))

**Comment by MambaDev** [comment]
You need to update the .env file to be the correct details to connect to postgres.

**Comment by VerumEmanio** [comment]
Hi @MambaDev,

Turns out that I hadn't updated my fork since before your readme and API overhaul, so I updated my fork from the devwars master and decided to start from the beginning. Running `npm run install` returns `npm ERR! missing script: install`. I opened Package.json and don't see an install script.

**Comment by MambaDev** [comment]
@VerumEmanio  `to install dependent node_modules.`. This is talking about the core npm install not a package based one. so just `npm install`. Read me has been adjusted to be more clear.

**Comment by VerumEmanio** [comment]
@MambaDev For the time being I'm stuck trying to run `npm run seed`, which returns `(node:260) UnhandledPromiseRejectionWarning: error: password authentication failed for user "MYounge"`. I've updated the .env file to use the same username and password as the one I set in pgAdmin, and in the SQL shell I can connect to the servers as myounge. I'm going to continue investigating the source of the problem, but until I get this fixed I don't see how I'll be able to contribute more to the documentation :(
