### ISSUE TITLE
Can't view other users' profiles even when logged in

### ISSUE THREAD

**Issue by ChrisRu** [DevWars/devwars-api#352]
Even when a regular user is logged in, the site gives an unauthorized error when visiting another player's dashboard.

Technical details:
When opening a user on `/dashboard/:id`, `GET /users/:id/statistics` loads fine, but the `GET /users/:id/activities` fails with a 403. 

Steps to reproduce:
1. Log in as non moderator
2. Go to `/games`
3. Open one of the games
4. Click on a player name

**Comment by MambaDev** [comment]
Thanks Chris!

This has now been resolved in the following [commit](https://github.com/DevWars/devwars-api/commit/5a008df2951891e99eceedee6b762bb40488d9e3) and will be rolled out when the next patch goes live.

Thanks.
